services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MENU_VERSION=1.9.9 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
      - NGINX_PORT=80 #optional
      - WEB_APP_PORT=3000 #optional
      - NODE_EXTRA_CA_CERTS=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    volumes:
      - ./config:/config
      - ./assets:/assets #optional
      - ./certs/tls-ca-bundle.pem:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    ports:
      # - 3000:3000
      - 69:69/udp
      # - 8080:80 #optional
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pxe.rule=Host(`pxe.$HOST`)
      - traefik.http.routers.pxe.entrypoints=http
      - traefik.http.services.pxe.loadbalancer.server.port=3000
