# version: '3.9'
services:
  drawio:
    image: jgraph/drawio
    # ports:
    #     - '8443:8443'
    #     - '8080:8080'
    container_name: drawio
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio.rule=Host(`drawio.$HOST`)
      - traefik.http.routers.drawio.entrypoints=http
      - traefik.http.services.drawio.loadbalancer.server.port=8080
    environment:
      - DRAWIO_SELF_CONTAINED=1
      - EXPORT_URL=http://export.$HOST/
      - DRAWIO_BASE_URL=draw.$HOST
    depends_on:
      - image-export
  image-export:
    container_name: image-export
    image: jgraph/export-server
    # ports:
    # - "8000:8000"
    environment:
      - DRAWIO_BASE_URL=draw.$HOST
    labels:
      - traefik.enable=true
      - traefik.http.routers.export.rule=Host(`export.$HOST`)
      - traefik.http.routers.export.entrypoints=http
      - traefik.http.services.export.loadbalancer.server.port=8000
