services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    # ports:
    #   - 81:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.who.rule=Host(`who.localhost`)
      - traefik.http.routers.who.entrypoints=http
      - traefik.http.services.who.loadbalancer.server.port=80
