# version: "3"
services:
  app:
    image: mattermost/focalboard
    container_name: focalboard
    volumes:
      - fbdata:/opt/focalboard/data
    # ports:
    #   - 80:8000
    environment:
      - VIRTUAL_HOST=board.localhost
      - VIRTUAL_PORT=8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.board.rule=Host(`board.localhost`)
      - traefik.http.routers.board.entrypoints=http
      - traefik.http.services.board.loadbalancer.server.port=8000

volumes:
  fbdata:


networks:
  default:
    name: main
    external: true
