# version: "3.8"
volumes:
  db_storage:
  n8n_storage:

services:
  n8n-db:
    image: postgres:16
    container_name: n8n-db
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=changeUser
      - POSTGRES_PASSWORD=changePassword
      - POSTGRES_NON_ROOT_USER=changeUser
      - POSTGRES_NON_ROOT_PASSWORD=changePassword
    volumes:
      - db_storage:/var/lib/postgresql/data
      # - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U changeUser -d changePassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      - traefik.enable=true
      # - traefik.http.routers.n8n-db.rule=Host(`n8n-db.$HOST`)
      # - traefik.http.routers.n8n-db.entrypoints=http
      # - traefik.http.services.n8n-db.loadbalancer.server.port=443

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=changeUser
      - DB_POSTGRESDB_PASSWORD=changePassword
      - N8N_SECURE_COOKIE=false
    # ports:
    #   - 5678:5678
    links:
      - n8n-db
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      n8n-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.$HOST`)
      - traefik.http.routers.n8n.entrypoints=http
      - traefik.http.services.n8n.loadbalancer.server.port=5678
