# version: "3"
services:
  focalboard:
    image: mattermost/focalboard:${FOCALBOARD_VERSION:-latest}
    container_name: focalboard
    volumes:
      - ${FOCALBOARD_DATA_DIR:-fbdata}:/opt/focalboard/data
    # ports:
    #   - 80:8000
    environment:
      - VIRTUAL_HOST=board.$HOST
      - VIRTUAL_PORT=8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.board.rule=Host(`board.$HOST`)
      - traefik.http.routers.board.entrypoints=http
      - traefik.http.services.board.loadbalancer.server.port=8000
      - kuma.board.http.name=Focalboard
      - kuma.board.http.url=http://focalboard:8000

volumes:
  fbdata:
    name: fbdata
    external: false
