services:
  directus:
    image: directus/directus:${DIRECTUS_VERSION:-latest}
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - .env
    environment:
      SECRET: "${SECRET}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      WEBSOCKETS_ENABLED: "true"
    labels:
      - traefik.enable=true
      - traefik.http.routers.lowdb.rule=Host(`lowdb.$HOST`)
      - traefik.http.routers.lowdb.entrypoints=http
      - traefik.http.services.lowdb.loadbalancer.server.port=8055
      - kuma.lowdb.http.name=Directus
      - kuma.lowdb.http.url=http://directus:8055
