services:
  changedetection:
    image: dgtlmoon/changedetection.io
    container_name: changedetection
    volumes:
      - "./data:/datastore"
    # ports:
    #   - "127.0.0.1:5000:5000"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.change.rule=Host(`change.$HOST`)
      - traefik.http.routers.change.entrypoints=http
      - traefik.http.services.change.loadbalancer.server.port=5000
