services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.5
    container_name: traefik
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - $DOCKER_DIR:/var/run/docker.sock:z
      # - /var/run/docker.sock:/var/run/docker.sock:z
      # - /run/podman/podman.sock:/var/run/docker.sock:Z
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy.rule=Host(`proxy.$HOST`)
      - traefik.http.routers.proxy.entrypoints=http
      - traefik.http.services.proxy.loadbalancer.server.port=8080
