services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    # ports:
    #   - 9283:80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.grocy.rule=Host(`grocy.$HOST`)
      - traefik.http.routers.grocy.entrypoints=http
      - traefik.http.services.grocy.loadbalancer.server.port=80
