services:
  trilium:
    image: triliumnext/notes:latest
    container_name: trilium
    restart: unless-stopped
    # environment:
    # - TRILIUM_DATA_DIR=/home/node/trilium-data
    # ports:
    # - '8180:8080'
    volumes:
      - ${TRILIUM_DATA_DIR:-tril-data}:/home/node/trilium-data
      # - tril-data/styles:/usr/src/app/styles
    labels:
      - traefik.enable=true
      - traefik.http.routers.wiki.rule=Host(`wiki.$HOST`)
      - traefik.http.routers.wiki.entrypoints=http
      - traefik.http.services.wiki.loadbalancer.server.port=8080

volumes:
  tril-data:
    name: tril-data
    external: true
