services:
  trilium:
    image: triliumnext/notes:latest
    container_name: trilium
    restart: always
    # environment:
    # - TRILIUM_DATA_DIR=/home/node/trilium-data
    # ports:
    # - '8180:8080'
    volumes:
      - ${TRILIUM_DATA_DIR:-tril-data}:/home/node/trilium-data
      # - tril-data/styles:/usr/src/app/styles
    labels:
      - traefik.enable=true
      - traefik.http.routers.notes.rule=Host(`notes.$HOST`)
      - traefik.http.routers.notes.entrypoints=http
      - traefik.http.services.notes.loadbalancer.server.port=8080

volumes:
  tril-data:
    name: tril-data
    external: true
