services:
  remote-rhel:
    image: remote-rhel
    container_name: remote-rhel
    build:
      ## Modify these for your specific case
      context: .
      dockerfile: Dockerfile
      args:
        ## Don't use quotes on these values
        - MAINTAINER=Douglas Shoemaker
        - APP_NAME=Remote-Rhel
        - DESC=A VNC/RDP RHEL 8 image
        - APP_VERSION=v0.1
        - BUILD_DATE=28-10-2024
        - DOCS=https://github.com/Godu92/Remote-Rhel/remoteRhel/README.md
        - LICENSES=N/A
        - REVISION=N/A
        - SOURCE=https://github.com/venera-13/jump-rhel
        - URL=https://github.com/Godu92/Remote-Rhel
        - VENDOR=N/A
        ## Username and password for the user
        - USER=user
        - PASS=password
        ## Set the timezone (from: /usr/share/zoneinfo)
        - TZ=America/New_York
        ## Set the subject of the self-signed SSL-certificate
        - KEYSUBJECT=/C=NL/ST=NAme/L=Location/O=Corp/OU=MyOU/CN=jump
        ## Set to "true" to force encryption on TigerVNC-server over TCP/5901. Note: this breaks noVNC and some VNC clients.
        - VNCTLS=false
    ports:
      - 42313:3389
      - 42419:5901
      - 41811:8080
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.remote.rule=Host(`remote.localhost`)
      - traefik.http.routers.remote.entrypoints=http
      - traefik.http.services.remote.loadbalancer.server.port=41811
