services:
  freeipa:
    image: freeipa/freeipa-server:fedora-41
    container_name: freeipa
    hostname: ipa.lab.localhost
    restart: unless-stopped

    privileged: true

    tmpfs:
      - /run
      - /tmp

    environment:
      - container=docker
      - IPA_SERVER_HOSTNAME=ipa.lab.localhost
      - IPA_SERVER_INSTALL_OPTS=--unattended --domain=lab.localhost --realm=LAB.LOCALHOST --ds-password=DirectoryManagerPassword123 --admin-password=AdminPassword123 --no-ntp --no-host-dns

    volumes:
      - ./data:/data
    # Only expose to Docker network, not host
    # Swap to `ports:` if needed outside
    expose:
      - "389" # LDAP
      - "636" # LDAPS
      - "88" # Kerberos
      - "464" # Kerberos password

    labels:
      - traefik.enable=true
      # HTTP service for web UI
      - traefik.http.routers.ipa.rule=Host(`ipa.lab.${HOST}`)
      - traefik.http.routers.ipa.entrypoints=http
      - traefik.http.services.ipa.loadbalancer.server.port=80

      # Optional: HTTPS service
      # - traefik.http.routers.ipa-secure.rule=Host(`ipa.lab.${HOST}`)
      # - traefik.http.routers.ipa-secure.entrypoints=https
      # - traefik.http.routers.ipa-secure.tls=true
