services:
  freeipa:
    image: freeipa/freeipa-server:latest
    container_name: freeipa
    hostname: ipa.${HOST}
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    command:
      - -U
      - --domain=${HOST}
      - --realm=${HOST^^}
      - --no-ntp
      - --no-dnssec-validation
    environment:
      - IPA_SERVER_HOSTNAME=ipa.${HOST}
      - TZ=America/New_York
      - PASSWORD=YourSecureAdminPassword
    volumes:
      - ./data:/data
    # Only expose to Docker network, not host
    # Swap to `ports:` if needed outside
    expose:
      - "389" # LDAP
      - "636" # LDAPS
      - "88" # Kerberos
      - "464" # Kerberos password

    labels:
      - traefik.enable=true
      # HTTP service for web UI
      - traefik.http.routers.ipa.rule=Host(`ipa.${HOST}`)
      - traefik.http.routers.ipa.entrypoints=http
      - traefik.http.services.ipa.loadbalancer.server.port=80

      # Optional: HTTPS service
      # - traefik.http.routers.ipa-secure.rule=Host(`ipa.${HOST}`)
      # - traefik.http.routers.ipa-secure.entrypoints=https
      # - traefik.http.routers.ipa-secure.tls=true
