services:
  wxrdle:
    image: adimartha/wxrdle
    container_name: wxrdle
    # ports:
    #     - 4011:80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordle.rule=Host(`wordle.$HOST`)
      - traefik.http.routers.wordle.entrypoints=http
      - traefik.http.services.wordle.loadbalancer.server.port=80
