services:
  whoami:
    image: traefik/whoami:${WHOAMI_VERSION:-latest}
    container_name: whoami
    # ports:
    #   - 81:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.who.rule=Host(`who.$HOST`)
      - traefik.http.routers.who.entrypoints=http
      - traefik.http.services.who.loadbalancer.server.port=80
      - kuma.who.http.name=whoami
      - kuma.who.http.url=http://whoami:80
