name: gopeed
services:
  gopeed:
    command: []
    container_name: gopeed
    deploy:
      resources:
        limits:
          memory: 256M
    hostname: gopeed
    image: liwei2633/gopeed:v1.5.7
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gopeed/icon.png
      traefik.enable: "true"
      traefik.http.routers.gopeed.rule: Host(`gopeed.universe-sal.duckdns.org`)
      traefik.http.services.gopeed.loadbalancer.server.port: "9999"
    # ports:
    #   - target: 9999
    #     published: "9999"
    #     protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /app/storage
      - type: bind
        source: ../downloads
        target: /app/Downloads
    x-casaos:
      ports:
        - container: "9999"
          description:
            en_us: WebUI HTTP Port
          protocol: tcp
      volumes:
        - container: /app/storage
          description:
            en_us: Gopeed data folder
        - container: /app/Downloads
          description:
            en_us: Gopeed download folder
    devices: []
    cap_add: []
    environment: []
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: joaobosconff
  category: Utilities
  description:
    en_us: Gopeed (full name Go Speed), a high-speed downloader developed by Golang
      + Flutter, supports (HTTP, BitTorrent, Magnet) protocol, and supports all
      platforms. In addition to basic download functions, Gopeed is also a
      highly customizable downloader that supports implementing more features
      through integration with APIs or installation and development of
      extensions.
  developer: GopeedLab
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gopeed/icon.png
  index: /
  is_uncontrolled: false
  main: gopeed
  port_map: "9999"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gopeed/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gopeed/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gopeed/screenshot-3.png
  store_app_id: gopeed
  tagline:
    en_us: Open source, lightweight, native, supports (HTTP, BitTorrent, Magnet ,
      etc.) for downloading.
  title:
    custom: Gopeed (9999)
    en_us: Gopeed

networks:
  default:
    name: proxy
    external: true
