# version: "3.9"

x-backend: &common
  image: papermerge/papermerge:${PAPERMERGE_VERSION:-latest}
  environment:
    PAPERMERGE__SECURITY__SECRET_KEY: ${PAPERMERGE__SECURITY__SECRET_KEY}
    PAPERMERGE__AUTH__USERNAME: admin
    PAPERMERGE__AUTH__PASSWORD: ${PAPERMERGE__AUTH__PASSWORD}
    PAPERMERGE__DATABASE__URL: postgresql://user:${POSTGRES_PASSWORD}@papermerge-db:5432/data
    PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  volumes:
    - ${PAPERMERGE_INDEX_DIR:-index_db}:/core_app/index_db
    - ${PAPERMERGE_MEDIA_DIR:-media}:/core_app/media
services:
  web:
    <<: *common
    # ports:
    #   - "12000:80"
    container_name: papermerge
    depends_on:
      papermerge-db:
        condition: service_healthy
      papermerge-redis:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.paper.rule=Host(`paper.$HOST`)
      - traefik.http.routers.paper.entrypoints=http
      - traefik.http.services.paper.loadbalancer.server.port=80
      - kuma.paper.http.name=Papermerge
      - kuma.paper.http.url=http://papermerge:80
  worker:
    <<: *common
    command: worker
    container_name: papermerge-worker
  papermerge-redis:
    image: redis:${REDIS_VERSION:-latest}
    container_name: papermerge-redis
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  papermerge-db:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: papermerge-db
    volumes:
      - ${PAPERMERGE_DB_DIR:-postgres_data}:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: data
      POSTGRES_USER: user
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    name: papermerge_postgres_data
    external: false
  index_db:
    name: papermerge_index_db
    external: false
  media:
    name: papermerge_media
    external: false
