## Group: ai.
include:
  - ollama/docker-compose.yaml
  - notebook/opennotebook-single/docker-compose.yaml
  - webui/docker-compose.yaml
  - comfyui/docker-compose.yaml
  - automatic1111/docker-compose.yaml
