services:
  jenkins:
    image: 'jenkinsci/blueocean:latest'
    container_name: jenkins
    # ports:
    #   - '${JENKINS_HTTP_PORT}:8080'
    #   - '${JENKINS_HTTPS_PORT}:8443'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
    environment:
      - 'JENKINS_OPTS=--httpPort=8080 --httpsPort=8443'
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.$HOST`)
      - traefik.http.routers.jenkins.entrypoints=http
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
volumes:
  jenkins_data:
    driver: local