# version: '3.9'
services:
  jenkins:
    image: "local/jenkins:latest"
    restart: always
    container_name: jenkins
    volumes:
      - ./data:/var/jenkins_home
      # - ./certs:/usr/local/share/ca-certificates/ # Uncomment if extra certs are needed
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.$HOST`)
      - traefik.http.routers.jenkins.entrypoints=http
      - traefik.http.services.jenkins.loadbalancer.server.port=8080

  # Use this to install/update plugins
  jenkins-updates:
    build:
      context: .
      dockerfile: Dockerfile
    image: "local/jenkins:latest"
    network_mode: "host"
    container_name: jenkins
    restart: always
    volumes:
      - ./data:/var/jenkins_home
      # - ./certs:/usr/local/share/ca-certificates/ # Uncomment if extra certs are needed
    profiles:
      - updates
    # Optional: override entrypoint to keep it running
    # command: tail -f /dev/null
