services:
  app:
    image: monica
    depends_on:
      - db
    # ports:
    #   - 8081:80
    environment:
      - APP_KEY=
      - DB_HOST=db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
    volumes:
      - data:/var/www/html/storage
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.people.rule=Host(`people.localhost`)
      - traefik.http.routers.people.entrypoints=http
      - traefik.http.services.people.loadbalancer.server.port=80

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    labels:
      - traefik.enable=true

networks:
  default:
    name: main
    external: true

volumes:
  data:
    name: data
  mysql:
    name: mysql
