services:
  monica:
    image: monica
    container_name: monica
    # ports:
    #   - 8081:80
    environment:
      - APP_KEY=base64:Zu1bDO3IWoL2/JVShYPLk7rATdkb+9PXg7fMQSmkvwk=
      - DB_HOST=monica-db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
    volumes:
      - ${MONICA_DIR:-data}:/var/www/html/storage
    depends_on:
      monica-db:
        condition: service_healthy
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.people.rule=Host(`people.$HOST`)
      - traefik.http.routers.people.entrypoints=http
      - traefik.http.services.people.loadbalancer.server.port=80

  monica-db:
    image: mariadb:10.11
    container_name: monica-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    volumes:
      - ${MONICA_DB_DIR:-mysql}:/var/lib/mysql
    restart: always
    command: >
      --innodb-force-recovery=1
      --skip-grant-tables
      --skip-networking=false
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 60s
    labels:
      - traefik.enable=true

volumes:
  data:
    name: data
    external: false
  mysql:
    name: mysql
    external: false
