services:
  app:
    image: monica
    container_name: monica
    # ports:
    #   - 8081:80
    environment:
      - APP_KEY=base64:Zu1bDO3IWoL2/JVShYPLk7rATdkb+9PXg7fMQSmkvwk=
      - DB_HOST=db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
    volumes:
      - data:/var/www/html/storage
    depends_on:
      - db
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.people.rule=Host(`people.localhost`)
      - traefik.http.routers.people.entrypoints=http
      - traefik.http.services.people.loadbalancer.server.port=80

  db:
    image: mariadb:11
    container_name: monica-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    labels:
      - traefik.enable=true

volumes:
  data:
    name: data
    external: true
  mysql:
    name: mysql
    external: true
