services:
  ttdybridge:
    image: "cp0204/ttdybridge:latest"
    restart: unless-stopped
    privileged: true
    pid: host
    volumes:
      - "/opt:/opt"
    environment:
      - PORT=2222
    container_name: ttdybridge
    labels:
      - traefik.enable=true
      - traefik.http.routers.terminal.rule=Host(`terminal.$HOST`)
      - traefik.http.routers.terminal.entrypoints=http
      - traefik.http.services.terminal.loadbalancer.server.port=2222
